# Generated by Django 5.2.5 on 2025-08-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('opening_crawl', models.TextField()),
                ('release_year', models.IntegerField()),
                ('fan_score', models.IntegerField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id_planet', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'planet',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('pk', models.CompositePrimaryKey('id_movie', 'id_person', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.DO_NOTHING, to='api.movie')),
                ('id_person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='api.person')),
            ],
            options={
                'db_table': 'movie_person',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='id_director',
            field=models.ForeignKey(db_column='id_director', on_delete=django.db.models.deletion.DO_NOTHING, to='api.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='id_producer',
            field=models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_id_producer_set', to='api.person'),
        ),
        migrations.CreateModel(
            name='MoviePlanet',
            fields=[
                ('pk', models.CompositePrimaryKey('id_movie', 'id_planet', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.DO_NOTHING, to='api.movie')),
                ('id_planet', models.ForeignKey(db_column='id_planet', on_delete=django.db.models.deletion.DO_NOTHING, to='api.planet')),
            ],
            options={
                'db_table': 'movie_planet',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='id_role',
            field=models.ForeignKey(blank=True, db_column='id_role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.role'),
        ),
    ]
